# Cargo configuration for TensorLogic

[build]
# Use all available CPU cores for compilation
jobs = 8

# Note: Metal GPU tests require single-threaded execution
# Run tests with: cargo test -- --test-threads=1
# See: claudedocs/metal_backward_pass_investigation.md
