# Cargo configuration for TensorLogic

[build]
# Use all available CPU cores for compilation
jobs = 8

# Note: Metal GPU tests require single-threaded execution
# Run tests with: cargo test -- --test-threads=1
#
# This is because Metal GPU access has race conditions when
# multiple tests try to use the GPU simultaneously.
#
# The .cargo/config.toml cannot set test-threads globally,
# so you must pass it as a command-line argument.
